name: shoyo
description: "Save files from the Android Share Sheet to local storage."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  permission_handler: ^11.1.0
  flutter_sharing_intent: ^1.1.0
  fluttertoast: ^8.2.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/graphics/icon.png"

flutter:
  uses-material-design: true